name: IIS Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Deploy to IIS
        shell: powershell
        run: |
          Import-Module WebAdministration

          # 1. Leállítás hibaellenőrzés nélkül
          # Az "-ErrorAction SilentlyContinue" megakadályozza a script leállását, ha a pool már áll
          Stop-WebAppPool -Name "Petrik1" -ErrorAction SilentlyContinue

          # 2. Várakozás a fájlok felszabadítására
          Start-Sleep -s 3

          # 3. MÁSOLÁS - Itt a ./dist/* a lényeg!
          # Használjuk a teljes elérési utat a biztonság kedvéért
          Copy-Item -Path "C:\Users\Administrator\Desktop\PETRIK1\_work\information-desk\information-desk\dist\*" -Destination "C:\Users\Administrator\Desktop\PETRIK1\dist" -Recurse -Force

          # 4. Újraindítás
          Start-WebAppPool -Name "Petrik1"
